# Generated by Django 4.2.13 on 2024-07-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email_address',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userdata',
            name='university',
            field=models.TextField(default='University'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='university_url',
            field=models.URLField(default='https://university.com'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(default='First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='github_username',
            field=models.CharField(default='Github Username', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='linkedin_url',
            field=models.URLField(default='https://linkedin.com'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='qualification',
            field=models.TextField(default='Qualification'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='summary',
            field=models.TextField(default='Summary'),
        ),
    ]
