# Generated by Django 4.2.13 on 2024-07-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0003_userdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
