# Generated by Django 4.2.13 on 2024-07-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0004_alter_userdata_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='githubDescriptionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
