# Generated by Django 4.2.13 on 2024-07-19 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0006_page_description_text_delete_githubdescriptiontext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_url',
        ),
        migrations.AddField(
            model_name='publication',
            name='abs_url',
            field=models.URLField(default='https://arxiv.org/abs/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='arxiv_url',
            field=models.URLField(default='https://arxiv.org/pdf/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='bib_url',
            field=models.URLField(default='https://arxiv.org/pdf/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pdfFile',
            field=models.FileField(blank=True, default='', upload_to='publication_pdfs'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(default='Authors', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(default=datetime.date(2024, 7, 19)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_image',
            field=models.ImageField(blank=True, default='', upload_to='publication_images'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.DeleteModel(
            name='publicationLinks',
        ),
    ]
