# Generated by Django 4.2.13 on 2024-07-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0007_remove_publication_publication_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='abs_url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='bib_url',
        ),
        migrations.AddField(
            model_name='publication',
            name='abs',
            field=models.TextField(default='Abstract'),
        ),
        migrations.AddField(
            model_name='publication',
            name='bib',
            field=models.TextField(default='BibTex'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
