# Generated by Django 4.2.13 on 2024-07-20 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0008_remove_publication_abs_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 20, 13, 7, 45, 325113, tzinfo=datetime.timezone.utc)),
        ),
    ]
