# Generated by Django 4.2.13 on 2024-07-20 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0009_alter_publication_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
