# Generated by Django 4.2.13 on 2024-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0010_publication_doi_alter_publication_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_year', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('students_level', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
                ('course_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='page_description_text',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
