# Generated by Django 4.2.13 on 2024-07-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0011_courses_alter_page_description_text_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_url',
        ),
    ]
