# Generated by Django 4.2.13 on 2024-07-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0013_experience_generalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
