# Generated by Django 4.2.13 on 2024-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0014_experience_experience_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='selected_gitlab_repos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='gitlab_id',
            field=models.CharField(default='gitlab_id', max_length=100),
        ),
    ]
