# Generated by Django 4.2.13 on 2024-07-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0017_rename_gitlab_id_gitlab_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='google_scholar_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('authors', models.TextField(default='')),
                ('publication', models.TextField(default='')),
                ('year', models.IntegerField()),
                ('cited_by', models.IntegerField()),
                ('citation_id', models.CharField(default='', max_length=100)),
                ('isSelected', models.BooleanField(default=False)),
                ('link', models.URLField(default='')),
            ],
        ),
    ]
