# Generated by Django 4.2.13 on 2024-07-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0018_google_scholar_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='gs_article_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, default='', upload_to='gs_pdfs')),
            ],
        ),
        migrations.AddField(
            model_name='google_scholar_article',
            name='article_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_interface.gs_article_data'),
        ),
    ]
