# Generated by Django 4.2.13 on 2024-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0020_alter_google_scholar_article_cited_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='darkmode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darkmode', models.BooleanField(default=False)),
            ],
        ),
    ]
