# Generated by Django 4.2.13 on 2024-07-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0021_darkmode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='darkmode',
        ),
    ]
