# Generated by Django 4.2.13 on 2024-07-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0022_delete_darkmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='gs_citation_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_id', models.CharField(max_length=100)),
            ],
        ),
    ]
