# Generated by Django 4.2.13 on 2024-07-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0023_gs_citation_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google_scholar_article',
            name='article_data',
        ),
        migrations.AddField(
            model_name='gs_citation_ids',
            name='pdf',
            field=models.FileField(blank=True, default='', upload_to='gs_pdfs'),
        ),
        migrations.AlterField(
            model_name='google_scholar_article',
            name='cited_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='gs_article_data',
        ),
    ]
