# Generated by Django 4.2.13 on 2024-07-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0024_remove_google_scholar_article_article_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='publication_videos'),
        ),
    ]
