# Generated by Django 4.2.13 on 2024-07-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0025_publication_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='gs_citation_ids',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='gs_videos'),
        ),
    ]
