# Generated by Django 4.2.13 on 2024-07-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0026_gs_citation_ids_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_me_selected_publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.publication')),
            ],
        ),
        migrations.CreateModel(
            name='about_me_selected_gs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.google_scholar_article')),
            ],
        ),
    ]
