# Generated by Django 4.2.13 on 2024-07-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0027_about_me_selected_publications_about_me_selected_gs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='showGithubUser',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
