# Generated by Django 4.2.13 on 2024-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0029_news_image_news_pdf_news_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='onload_animation',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
