# Generated by Django 4.2.13 on 2024-08-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0030_userdata_onload_animation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='phone',
        ),
    ]
