# Generated by Django 4.2.13 on 2024-08-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0031_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(default='', max_length=100)),
                ('type', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_interface.skill_type')),
            ],
        ),
    ]
