# Generated by Django 4.2.13 on 2024-08-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0031_remove_generalinfo_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_scholar_article',
            name='date_added',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
