# Generated by Django 4.2.13 on 2024-08-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0032_google_scholar_article_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='google_scholar_article',
            old_name='date_added',
            new_name='pub_date',
        ),
    ]
