# Generated by Django 4.2.13 on 2024-08-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0033_rename_date_added_google_scholar_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me_selected_publications',
            name='add_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='google_scholar_article',
            name='pub_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
