# Generated by Django 4.2.13 on 2024-08-10 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0035_remove_google_scholar_article_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me_selected_publications',
            name='add_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
